# Generated by Django 5.1.4 on 2025-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_shoes_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='prize',
        ),
        migrations.AddField(
            model_name='shoes',
            name='brand',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
