# Generated by Django 5.1.4 on 2025-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_remove_shoes_genre_remove_shoes_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe_images/'),
        ),
    ]
